name: ProxyPatternPool Package

on:
  push:
    branches: [ main ]
  # push_request: ?

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # broken: pypy3.7
        # broken: 3.7 (pymarkdownlnt)
        # 3.8 and 3.9: needs more Typing
        # 3.12-dev: issue with mypy
        python-version: ["3.10", "3.11"]
    steps:
    # Setup
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    # Dependencies
    - name: Install Python Dependencies
      run: |
        pip install -U pip
        pip install -e .[local,dev]
    # Checks
    - name: Check with mypy
      run: make check.mypy
    # - name: Check with black
    #  run: black --check ProxyPatternPool.py
    - name: Check with flake8
      run: make check.flake8
    - name: Check with pytest
      run: make check.pytest
    - name: Check with coverage
      run: |
        coverage run -m pytest --log-level=debug --capture=tee-sys test.py
        coverage report --fail-under=100 --include=ProxyPatternPool.py
    - name: Check with pymarkdown
      run: pymarkdown scan *.md
